# version: '3.8' # the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

services:
  ################# DOWNLOAD MY APP FROM DOCKER HUB #################
  app:
    image: alessiofontanarossa/machineinnovators_monitoring:latest
    container_name: backend_api
    ports:
      - "7500:8080"
    volumes:
      - ./data:/working_dir/data # to mount the data folder in the container
    restart: unless-stopped

  ################# USE GRAFANA FOR DATA MONITORING #################
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment: # install CSV plugin to read sentiment.csv
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
     
volumes:
  grafana-storage: {}
